/**
 * ArgonFetch.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MediaType = 0 | 1;

export const MediaType = {
    NUMBER_0: 0 as MediaType,
    NUMBER_1: 1 as MediaType
};

