/**
 * ArgonFetch.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MediaInformationDto { 
    requestedUrl: string | null;
    streamingUrl: string | null;
    coverUrl: string | null;
    title: string | null;
    author: string | null;
}

