/**
 * ArgonFetch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MusicInformation { 
    streaming_url: string;
    song_url: string;
    song_name: string;
    author: string;
    image_url: string;
}

