/**
 * ArgonFetch.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaInformationDto } from './mediaInformationDto';
import { MediaType } from './mediaType';


export interface ResourceInformationDto { 
    type: MediaType;
    title?: string | null;
    author?: string | null;
    coverUrl?: string | null;
    mediaItems: Array<MediaInformationDto> | null;
}
export namespace ResourceInformationDto {
}


