/**
 * ArgonFetch API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MusicInformation } from './musicInformation';


export interface PlaylistInformation { 
    playlist_name: string;
    author: string;
    image_url: string;
    songs: Array<MusicInformation>;
}

